# text 토큰화 시키는 방법


In [ ]:
from tensorflow.keras.preprocessing.text import text_to_word_sequence
text='해보지 않으면 해낼 수 없다'
print('text: ',text)
print('토큰화: ',text_to_word_sequence(text))

uimport nujnp

In [12]:
#토크나이저 클래스를 활용하여 단어를 토큰화 한 다음 단어의 개수를 셀 수 있음
from tensorflow.keras.preprocessing.text import Tokenizer
docs = ['먼저 텍스트의 각 단어를 토큰화 합니다.',
        '텍스트의 단어로 토큰화 해서 딥러닝에서 인식 됩니다.',
        '토큰화한 결과는 딥러닝에서 사용할 수 있습니다.']
token=Tokenizer()
token.fit_on_texts(docs) #토큰화 시킴
print(token.texts_to_sequences(docs))


[[4, 1, 5, 6, 2, 7], [1, 8, 2, 9, 3, 10, 11], [12, 13, 3, 14, 15, 16]]

In [47]:
print('\n',token.word_index) #단어마다 인덱스 설정

print('\n',token.index_word) #거꾸로

print('\n',token.word_counts) #단어마다의 갯수

print('\n',len(token.word_counts)) #토큰화한 각 단어의 출현 빈도수

print('\n',token.document_count) #문장의 수

print('\n',token.word_docs) # 단어마다 나오는 문장의 수


 {'텍스트의': 1, '토큰화': 2, '딥러닝에서': 3, '먼저': 4, '각': 5, '단어를': 6, '합니다': 7, '단어로': 8, '해서': 9, '인식': 10, '됩니다': 11, '토큰화한': 12, '결과는': 13, '사용할': 14, '수': 15, '있습니다': 16}

 {1: '텍스트의', 2: '토큰화', 3: '딥러닝에서', 4: '먼저', 5: '각', 6: '단어를', 7: '합니다', 8: '단어로', 9: '해서', 10: '인식', 11: '됩니다', 12: '토큰화한', 13: '결과는', 14: '사용할', 15: '수', 16: '있습니다'}

 OrderedDict([('먼저', 1), ('텍스트의', 2), ('각', 1), ('단어를', 1), ('토큰화', 2), ('합니다', 1), ('단어로', 1), ('해서', 1), ('딥러닝에서', 2), ('인식', 1), ('됩니다', 1), ('토큰화한', 1), ('결과는', 1), ('사용할', 1), ('수', 1), ('있습니다', 1)])

 16

 3

 defaultdict(<class 'int'>, {'텍스트의': 2, '합니다': 1, '각': 1, '토큰화': 2, '단어를': 1, '먼저': 1, '단어로': 1, '딥러닝에서': 2, '해서': 1, '됩니다': 1, '인식': 1, '수': 1, '있습니다': 1, '결과는': 1, '사용할': 1, '토큰화한': 1, 0: 0})


In [62]:
print(docs)

['먼저 텍스트의 각 단어를 토큰화 합니다.', '텍스트의 단어로 토큰화 해서 딥러닝에서 인식 됩니다.', '토큰화한 결과는 딥러닝에서 사용할 수 있습니다.']


In [84]:
def count_words(docs):
    result = {}
    for sentence in docs:
        words = sentence.split(' ')
        for word in words:
            if word in result:
                result[word] += 1
            else:
                result[word] = 1
    return result
result = count_words(docs)
for word ,cnt in result.items():
    print(f'{word}    :{cnt}') 


먼저    :1
텍스트의    :2
각    :1
단어를    :1
토큰화    :2
합니다.    :1
단어로    :1
해서    :1
딥러닝에서    :2
인식    :1
됩니다.    :1
토큰화한    :1
결과는    :1
사용할    :1
수    :1
있습니다.    :1


In [98]:
text = "먼저 텍스트의 각 단어를 토큰화 합니다. 단어로 토큰화해서 딥러닝에서 인식 됩니다. 토큰화한 결과는 사용할 수 있습니다."
word_count = {}
for word in text.split():
    word_count[word] = word_count.get(word, 0) + 1

max_word_len = max(len(word) for word in word_count.keys())
max_count_len = max(len(str(count)) for count in word_count.values())

for word, count in word_count.items():
    print("{:<{}}: {:>{}}".format(word, max_word_len, count, max_count_len))

먼저   : 1
텍스트의 : 1
각    : 1
단어를  : 1
토큰화  : 1
합니다. : 1
단어로  : 1
토큰화해서: 1
딥러닝에서: 1
인식   : 1
됩니다. : 1
토큰화한 : 1
결과는  : 1
사용할  : 1
수    : 1
있습니다.: 1


In [89]:
# 단어의 원-핫 인코딩
 
#1. 문장을 토크나이징 
# 2. 단어의 인덱스를 확인-> 변수에 추가
# 3. 단어의 인덱스 원핫 인코딩 -> 인덱스 갯수 +1 로 to_categorical

text='오랫동안 꿈꾸는 이는 그 꿈을 닮아간다.'mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm
token =Tokenizer()
token.fit_on_texts([text])
print(token.word_index)
x_index = token.texts_to_sequences([text]) #단어의 인덱스만 리스트로 반환

{'오랫동안': 1, '꿈꾸는': 2, '이는': 3, '그': 4, '꿈을': 5, '닮아간다': 6}


In [93]:
# x_index #에대해 원핫 인코딩
from tensorflow.keras.utils import to_categorical
to_categorical(x_index,num_classes=len(x_index[0])+1)

array([[[0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 0., 1.]]], dtype=float32)

In [126]:
#딥러닝을 활용한 자연어 처리
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten, Embedding
from tensorflow.keras.utils import to_categorical
import numpy as np

docs = ["너무 재밌네요","최고예요","참 잘 만든 영화예요","추천하고 싶은 영화입니다","한번 더 보고싶네요","글쎄요","별로예요","생각보다 지루하네요","연기가 어색해요","재미없어요"]


In [127]:
classes=np.array([1,1,1,1,1,0,0,0,0,0]) 

#자연어 전처리 -> 토큰화
token = Tokenizer()
token.fit_on_texts(docs)
print(token.word_index)

{'너무': 1, '재밌네요': 2, '최고예요': 3, '참': 4, '잘': 5, '만든': 6, '영화예요': 7, '추천하고': 8, '싶은': 9, '영화입니다': 10, '한번': 11, '더': 12, '보고싶네요': 13, '글쎄요': 14, '별로예요': 15, '생각보다': 16, '지루하네요': 17, '연기가': 18, '어색해요': 19, '재미없어요': 20}


In [128]:
x= token.texts_to_sequences(docs)
padded_x = pad_sequences(x,4)
print('패딩한 결과 출력 :',padded_x)

패딩한 결과 출력 : [[ 0  0  1  2]
 [ 0  0  0  3]
 [ 4  5  6  7]
 [ 0  8  9 10]
 [ 0 11 12 13]
 [ 0  0  0 14]
 [ 0  0  0 15]
 [ 0  0 16 17]
 [ 0  0 18 19]
 [ 0  0  0 20]]


In [ ]:
#임베딩에 입력된 단어의 수를 지정
word_size=len(token.word_index)+1
#단어 임베딩을 포함한 딥러닝 모델 생성
model =Sequential()
model.add(Embedding(word_size, 8,input_length=4))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 4, 8)              168       
                                                                 
 flatten (Flatten)           (None, 32)                0         
                                                                 
 dense (Dense)               (None, 1)                 33        
                                                                 
Total params: 201
Trainable params: 201
Non-trainable params: 0
_________________________________________________________________


In [138]:
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(padded_x,classes,batch_size=8,epochs=20)


Epoch 1/20
2/2 [==============================] - 1s 7ms/step - loss: 0.5065 - accuracy: 1.0000
Epoch 2/20
2/2 [==============================] - 0s 7ms/step - loss: 0.5022 - accuracy: 1.0000
Epoch 3/20
2/2 [==============================] - 0s 11ms/step - loss: 0.4983 - accuracy: 1.0000
Epoch 4/20
2/2 [==============================] - 0s 8ms/step - loss: 0.4947 - accuracy: 1.0000
Epoch 5/20
2/2 [==============================] - 0s 9ms/step - loss: 0.4913 - accuracy: 1.0000
Epoch 6/20
2/2 [==============================] - 0s 10ms/step - loss: 0.4877 - accuracy: 1.0000
Epoch 7/20
2/2 [==============================] - 0s 8ms/step - loss: 0.4844 - accuracy: 1.0000
Epoch 8/20
2/2 [==============================] - 0s 8ms/step - loss: 0.4809 - accuracy: 1.0000
Epoch 9/20
2/2 [==============================] - 0s 7ms/step - loss: 0.4775 - accuracy: 1.0000
Epoch 10/20
2/2 [==============================] - 0s 8ms/step - loss: 0.4741 - accuracy: 1.0000
Epoch 11/20
2/2 [====================

In [140]:
print('accuracy:{:.4f}'.format(model.evaluate(padded_x,classes)[1]))



1/1 [==============================] - 0s 66ms/step - loss: 0.4366 - accuracy: 1.0000
accuracy:1.0000


In [144]:
model.predict(padded_x[3].reshape(1,-1))


1/1 [==============================] - 0s 97ms/step


array([[0.73667485]], dtype=float32)